### PR TITLE
Show user's full name (GECOS)

### PR DESCRIPTION
**Pull request by oblitum**

### CODE REVIEW

**Comment by oblitum** [comment]
That's, when available.

**Comment by eayus** [comment]
Sorry for the awfully late reply. Honestly, I feel like this is more of a preference thing - I prefer it just to show my first name, but other's (like youself) may prefer the full name.

What I think might be best is to this is to add an option in the configuration file, where the user can choose to show either the first or full name.

**Comment by oblitum** [comment]
But it will only show your full name if you care to setup one, otherwise it will show just the username. Do you still think an option is needed? If a person don't like their full name around she probably won't set it up anyways.

**Comment by eayus** [comment]
Sorry for being insanely slow with this, been really busy lately. I'll merge this, but one concern I have is that the full name may be so long that it will overlap with the neighbouring users's name. I'll revisit that if it becomes an issue.

**Pull request merged**
